/* SPDX-License-Identifier: Apache License 2.0
 *
 * Copyright(c) 2023 Andrey Borisovich. All rights reserved.
 *
 * Author: Andrey Borisovich <andrey@borisovich.com>
 */
#pragma once
#ifdef WIN32

#include <iostream>
#include <windows.h>

namespace server_crud
{

BOOL WINAPI console_handler(_In_ DWORD dwCtrlType)
{
	switch(dwCtrlType)
	{
		// A CTRL + C signal was received, either from keyboard input or from a signal generated by the GenerateConsoleCtrlEvent function.
		case CTRL_C_EVENT:
			[[fallthrough]];
		// A CTRL + BREAK signal was received, either from keyboard input or from a signal generated by GenerateConsoleCtrlEvent.
		case CTRL_BREAK_EVENT:
			[[fallthrough]];

		// A signal that the system sends to all processes attached to a console when the user closes the console(either by clicking Close
		// on the console window's window menu, or by clicking the End Task button command from Task Manager).
		case CTRL_CLOSE_EVENT:
			std::exit(0);

		// A signal that the system sends to all console processes when a user is logging off.This signal does not indicate which user is
		// logging off, so no assumptions can be made.
		case CTRL_LOGOFF_EVENT:
			[[fallthrough]];

		// Note that this signal is received only by services.Interactive applications are terminated at logoff, so they are not present
		// when the system sends this signal.
		case CTRL_SHUTDOWN_EVENT:
			[[fallthrough]];
		default:
			return TRUE;
	}

	return TRUE;
}

}
#endif //WIN32